### ISSUE TITLE
Feature Request - Zoomable and Clickable Highlighted Screenshots in Video Search Results

### ISSUE THREAD

**Issue by keng2021** [shaunnarayan/cytev2#15] opened 2023-04-13 15:42 UTC
I hope this message finds you well. I am a user of your Cyte Screenshot app and appreciate its unique features and capabilities for knowledge management and easy history search. I am writing to propose a new feature that I believe would significantly enhance the user experience and the app's functionality.

Feature Description:
I would like to request a feature that allows users to zoom in on highlighted screenshots taken from videos and/or have the ability to click on the video result to open it at the specific time of the search result. Additionally, the searched words should be highlighted within the video or transcript, making it easier for users to visually identify the information they are looking for.

It is really hard to find the result from the video, users have to watch the whole video and try to find the result. 

Best regards,

**Comment by shaunnarayan** [comment] 2023-04-13 23:53
Thank you for raising this, you are absolutely right that Cyte should take you right to the specific time of the result and it should be highlighted when you press the expand button, this seems to be a regression I introduced in https://github.com/shaunnarayan/cytev2/commit/263c69dc4bed7cc877510df54c8850edaf3fceea

I'll work on getting this fixed ASAP

**Comment by shaunnarayan** [comment] 2023-04-14 08:00
Fixed in https://github.com/shaunnarayan/cytev2/commit/a1ecd8d0836681033c7195b6f56a91277c7333c4

Here's a demo of the expected functionality; the result goes to the exact timestamp with the target highlighted, and continues to highlight the search term even when scrolling the timeline
![Apr-14-2023 19-44-00](https://user-images.githubusercontent.com/16547695/231982142-7af0d487-044d-416c-8033-42effccbd049.gif)

**Closed by shaunnarayan** 2023-04-14 08:00 UTC
Labels: bug
